Output demo.gif

Set FontSize 12
Set Framerate 30
Set Height 1080

Set WindowBar Colorful
Set WindowBarSize 40

Set PlaybackSpeed 2.0

Hide
Type "go build -o hackertea ."
Enter
Sleep 28s

Type "clear"
Enter
Show


Type "./hackertea"
Enter
Sleep 10s

Down@500ms 5

Type "n"

Sleep 3s

Down@500ms 5
Up@500ms 5

Type "t"
Sleep 2s

Type "t"
Sleep 2s

Type "T"
Sleep 2s

Type "T"
Sleep 2s

Type "?"

Sleep 5s

Type "?"

# Admire the output for a bit.
Sleep 3s

Hide
Ctrl+C
Type "rm hackertea"
Enter
